### ISSUE TITLE
Next.js 14で追加された機能を確認し、適用する

### ISSUE THREAD

**Issue by L4Ph** [aipictors/aipictors#77]
[Next.js 14まとめ](https://zenn.dev/a_da_chi/articles/6235ef4b317368)

- [x]  [Turbopack](https://nextjs.org/docs/architecture/turbopack)
- [ ] [部分的プリレンダリング(Partial Prerendering)](https://nextjs.org/docs/app/api-reference/next-config-js/partial-prerendering)
- [x] Server Action

**Comment by Katsuyuki-Karasawa** [comment]
Turbopackから

```diff json
  "scripts": {
-   "dev": "next dev",
+  "dev": "next dev --turbo",
    "build": "next build",
    "prebuild": "graphql-codegen -c codegen.ts",
    "start": "next start",
    "test": "vitest --run",
    "test:watch": "vitest",
    "check": "tsc --noEmit",
    "refactor": "biome lint --apply-unsafe . && biome check --apply-unsafe . && biome format --write ."
  }
  ```

**Comment by Katsuyuki-Karasawa** [comment]
```bash
./app/globals.css:977:22
Parsing css source code failed
  975 | }
  976 | .max-w-\[container\.sm\] {
> 977 |   max-width: container.sm;
      |                       ^
  978 | }
  979 | .max-w-lg {
  980 |   max-width: 32rem;

Expected Declaration value
```

**Comment by reiwa** [comment]
globals.css はこのライブラリが上書きしています。 https://ui.shadcn.com/themes

**Comment by Katsuyuki-Karasawa** [comment]
shadcnのissue見てきます

**Comment by Katsuyuki-Karasawa** [comment]
この辺かな?

- https://github.com/shadcn-ui/ui/issues/194

**Comment by Katsuyuki-Karasawa** [comment]
```json
  "scripts": {
    "dev": "next dev",
    "turbo": "next dev --turbo",
    "build": "next build",
    "prebuild": "graphql-codegen -c codegen.ts",
    "start": "next start",
    "test": "vitest --run",
    "test:watch": "vitest",
    "check": "tsc --noEmit",
    "refactor": "biome lint --apply-unsafe . && biome check --apply-unsafe . && biome format --write ."
  }
```
とりあえず改善するまでは様子見

次、Partial Prerendering

**Comment by Katsuyuki-Karasawa** [comment]
Partial Prerenderingオフ

```bash
Route (app)                                               Size     First Load JS
┌ ○ /_not-found                                           0 B                0 B
├ λ /[lang]                                               4.71 kB         129 kB
├ λ /[lang]/about                                         244 B          82.4 kB
├ λ /[lang]/about/us                                      244 B          82.4 kB
├ λ /[lang]/account                                       4.13 kB         100 kB
├ λ /[lang]/account/login                                 1.66 kB         115 kB
├ λ /[lang]/account/password                              2.03 kB         112 kB
├ λ /[lang]/account/profile                               4.25 kB          93 kB
├ λ /[lang]/albums                                        718 B          89.5 kB
├ λ /[lang]/albums/[album]                                2.41 kB         100 kB
├ λ /[lang]/app                                           1.87 kB        91.2 kB
├ λ /[lang]/app/privacy                                   590 B            90 kB
├ λ /[lang]/app/support                                   590 B            90 kB
├ λ /[lang]/app/terms                                     590 B            90 kB
├ λ /[lang]/awards                                        1.37 kB        90.1 kB
├ λ /[lang]/awards/[year]/[month]                         867 B          83.1 kB
├ λ /[lang]/awards/[year]/[month]/[day]                   1.37 kB        90.1 kB
├ λ /[lang]/collections                                   143 B          91.8 kB
├ λ /[lang]/collections/[collection]                      1.71 kB         100 kB
├ λ /[lang]/events/wakiaiai                               3.14 kB         113 kB
├ λ /[lang]/events/wakiaiai2                              3.14 kB         113 kB
├ λ /[lang]/flutter/privacy                               244 B          82.4 kB
├ λ /[lang]/flutter/specified-commercial-transaction-act  243 B          82.4 kB
├ λ /[lang]/flutter/terms                                 244 B          82.4 kB
├ λ /[lang]/generation                                    20.4 kB         209 kB
├ λ /[lang]/generation/history                            3.15 kB         148 kB
├ λ /[lang]/generation/lite                               4.04 kB        92.8 kB
├ λ /[lang]/guideline                                     311 B          82.5 kB
├ λ /[lang]/idea                                          245 B          82.4 kB
├ λ /[lang]/messages                                      243 B          82.4 kB
├ λ /[lang]/messages/[recipient]                          2.83 kB         126 kB
├ λ /[lang]/models                                        2.1 kB         99.4 kB
├ λ /[lang]/models/[model]                                3.81 kB        99.8 kB
├ λ /[lang]/my/albums                                     3.8 kB          109 kB
├ λ /[lang]/my/albums/[album]                             4.14 kB         106 kB
├ λ /[lang]/my/collections                                384 B          82.6 kB
├ λ /[lang]/my/followees                                  1.46 kB         117 kB
├ λ /[lang]/my/followers                                  1.47 kB         117 kB
├ λ /[lang]/my/notes                                      244 B          82.4 kB
├ λ /[lang]/my/novels                                     245 B          82.4 kB
├ λ /[lang]/my/stickers                                   2.31 kB        91.1 kB
├ λ /[lang]/my/works                                      1.07 kB        89.8 kB
├ λ /[lang]/new/album                                     945 B           103 kB
├ λ /[lang]/new/image                                     24.3 kB         123 kB
├ λ /[lang]/new/text                                      249 B          82.4 kB
├ λ /[lang]/notes                                         244 B          82.4 kB
├ λ /[lang]/notes/[note]                                  244 B          82.4 kB
├ λ /[lang]/notifications                                 1.74 kB        90.5 kB
├ λ /[lang]/novels                                        244 B          82.4 kB
├ λ /[lang]/novels/[novel]                                245 B          82.4 kB
├ λ /[lang]/plus                                          5.91 kB         149 kB
├ λ /[lang]/plus/cancel                                   187 B          89.6 kB
├ λ /[lang]/plus/success                                  186 B          89.6 kB
├ λ /[lang]/privacy                                       245 B          82.4 kB
├ λ /[lang]/search                                        5.31 kB         128 kB
├ λ /[lang]/sensitive                                     244 B          82.4 kB
├ λ /[lang]/sensitive/albums                              3.08 kB          99 kB
├ λ /[lang]/sensitive/albums/[album]                      2.41 kB         100 kB
├ λ /[lang]/sensitive/awards                              867 B          83.1 kB
├ λ /[lang]/sensitive/awards/[year]/[month]               866 B          83.1 kB
├ λ /[lang]/sensitive/awards/[year]/[month]/[day]         1.37 kB        90.1 kB
├ λ /[lang]/sensitive/collections                         143 B          91.8 kB
├ λ /[lang]/sensitive/collections/[collection]            1.71 kB         100 kB
├ λ /[lang]/sensitive/themes                              3.08 kB          99 kB
├ λ /[lang]/sensitive/themes/[year]/[month]               3.08 kB          99 kB
├ λ /[lang]/sensitive/themes/[year]/[month]/[day]         244 B          82.4 kB
├ λ /[lang]/sensitive/works                               242 B          82.4 kB
├ λ /[lang]/sensitive/works/[work]                        170 B           144 kB
├ λ /[lang]/sensitive/works/2.5d                          3.39 kB         113 kB
├ λ /[lang]/sensitive/works/2d                            3.39 kB         113 kB
├ λ /[lang]/sensitive/works/3d                            3.39 kB         113 kB
├ λ /[lang]/series                                        244 B          82.4 kB
├ λ /[lang]/settings                                      244 B          82.4 kB
├ λ /[lang]/settings/interface                            897 B          93.6 kB
├ λ /[lang]/settings/muted/tags                           1.63 kB         115 kB
├ λ /[lang]/settings/muted/users                          988 B           114 kB
├ λ /[lang]/settings/notification                         999 B          93.7 kB
├ λ /[lang]/settings/request                              4.07 kB        92.8 kB
├ λ /[lang]/settings/restriction                          4.17 kB        92.9 kB
├ λ /[lang]/specified-commercial-transaction-act          245 B          82.4 kB
├ λ /[lang]/stamp-space                                   244 B          82.4 kB
├ λ /[lang]/stickers                                      155 B           107 kB
├ λ /[lang]/stickers/(..)stickers/[sticker]               2.06 kB         103 kB
├ λ /[lang]/stickers/[sticker]                            298 B          82.5 kB
├ λ /[lang]/stickers/downloads                            245 B          82.4 kB
├ λ /[lang]/stickers/search                               243 B          82.4 kB
├ λ /[lang]/stickers/search/[search]                      156 B           107 kB
├ λ /[lang]/support/chat                                  2.83 kB         126 kB
├ λ /[lang]/tags                                          244 B          82.4 kB
├ λ /[lang]/tags/[tag]                                    464 B          89.8 kB
├ λ /[lang]/terms                                         244 B          82.4 kB
├ λ /[lang]/themes                                        4.07 kB         100 kB
├ λ /[lang]/themes/[year]/[month]                         3.08 kB          99 kB
├ λ /[lang]/themes/[year]/[month]/[day]                   244 B          82.4 kB
├ λ /[lang]/users                                         243 B          82.4 kB
├ λ /[lang]/users/[user]                                  3.6 kB         99.6 kB
├ λ /[lang]/users/[user]/albums                           3.62 kB        99.6 kB
├ λ /[lang]/users/[user]/collections                      253 B          82.4 kB
├ λ /[lang]/users/[user]/notes                            251 B          82.4 kB
├ λ /[lang]/users/[user]/novels                           252 B          82.4 kB
├ λ /[lang]/users/[user]/stickers                         1.78 kB        97.7 kB
├ λ /[lang]/users/[user]/supports                         2.13 kB        90.9 kB
├ λ /[lang]/works                                         244 B          82.4 kB
├ λ /[lang]/works/[work]                                  171 B           144 kB
├ λ /[lang]/works/2.5d                                    3.39 kB         113 kB
├ λ /[lang]/works/2d                                      3.39 kB         113 kB
└ λ /[lang]/works/3d                                      3.39 kB         113 kB
+ First Load JS shared by all                             82.2 kB
  ├ chunks/4938-ce253e45956d07cf.js                       26.8 kB
  ├ chunks/fd9d1056-e2552509ebde8612.js                   53.3 kB
  ├ chunks/main-app-b22967817e229d15.js                   228 B
  └ chunks/webpack-87a61244e7aec903.js                    1.9 kB


ƒ Middleware                                              39.7 kB

○  (Static)   prerendered as static content
λ  (Dynamic)  server-rendered on demand using Node.js
```

**Comment by Katsuyuki-Karasawa** [comment]
Partial Prerenderingオン

```bash
Route (app)                                               Size     First Load JS
┌ ○ /_not-found                                           0 B                0 B
├ ◐ /[lang]                                               4.71 kB         130 kB
├ ◐ /[lang]/about                                         242 B          83.8 kB
├ ◐ /[lang]/about/us                                      243 B          83.8 kB
├ ◐ /[lang]/account                                       4.13 kB         102 kB
├ ○ /[lang]/account/login                                 1.66 kB         116 kB
├ ○ /[lang]/account/password                              2.03 kB         113 kB
├ ○ /[lang]/account/profile                               4.26 kB        94.5 kB
├ ◐ /[lang]/albums                                        721 B          90.9 kB
├ ◐ /[lang]/albums/[album]                                2.41 kB         101 kB
├ ◐ /[lang]/app                                           1.87 kB        92.7 kB
├ ◐ /[lang]/app/privacy                                   590 B          91.4 kB
├ ◐ /[lang]/app/support                                   590 B          91.4 kB
├ ◐ /[lang]/app/terms                                     590 B          91.4 kB
├ ◐ /[lang]/awards                                        1.37 kB        91.6 kB
├ ◐ /[lang]/awards/[year]/[month]                         866 B          84.5 kB
├ ◐ /[lang]/awards/[year]/[month]/[day]                   1.37 kB        91.6 kB
├ ◐ /[lang]/collections                                   143 B          93.3 kB
├ ◐ /[lang]/collections/[collection]                      1.71 kB         102 kB
├ ◐ /[lang]/events/wakiaiai                               3.14 kB         114 kB
├ ◐ /[lang]/events/wakiaiai2                              3.14 kB         114 kB
├ ◐ /[lang]/flutter/privacy                               242 B          83.8 kB
├ ◐ /[lang]/flutter/specified-commercial-transaction-act  244 B          83.8 kB
├ ◐ /[lang]/flutter/terms                                 243 B          83.8 kB
├ ◐ /[lang]/generation                                    20.4 kB         210 kB
├ ○ /[lang]/generation/history                            3.15 kB         149 kB
├ ◐ /[lang]/generation/lite                               4.04 kB        94.2 kB
├ ◐ /[lang]/guideline                                     311 B          83.9 kB
├ ◐ /[lang]/idea                                          242 B          83.8 kB
├ ◐ /[lang]/messages                                      243 B          83.8 kB
├ ◐ /[lang]/messages/[recipient]                          2.83 kB         128 kB
├ ◐ /[lang]/models                                        2.1 kB          101 kB
├ ◐ /[lang]/models/[model]                                3.82 kB         101 kB
├ ◐ /[lang]/my/albums                                     3.8 kB          110 kB
├ ◐ /[lang]/my/albums/[album]                             4.14 kB         107 kB
├ ◐ /[lang]/my/collections                                383 B            84 kB
├ ◐ /[lang]/my/followees                                  1.46 kB         118 kB
├ ◐ /[lang]/my/followers                                  1.47 kB         118 kB
├ ◐ /[lang]/my/notes                                      241 B          83.8 kB
├ ◐ /[lang]/my/novels                                     242 B          83.8 kB
├ ◐ /[lang]/my/stickers                                   2.31 kB        92.5 kB
├ ◐ /[lang]/my/works                                      1.07 kB        91.3 kB
├ ◐ /[lang]/new/album                                     945 B           105 kB
├ ◐ /[lang]/new/image                                     24.3 kB         124 kB
├ ◐ /[lang]/new/text                                      250 B          83.9 kB
├ ◐ /[lang]/notes                                         244 B          83.8 kB
├ ◐ /[lang]/notes/[note]                                  242 B          83.8 kB
├ ◐ /[lang]/notifications                                 1.75 kB        91.9 kB
├ ◐ /[lang]/novels                                        243 B          83.8 kB
├ ◐ /[lang]/novels/[novel]                                243 B          83.8 kB
├ ◐ /[lang]/plus                                          5.91 kB         151 kB
├ ◐ /[lang]/plus/cancel                                   187 B            91 kB
├ ◐ /[lang]/plus/success                                  186 B            91 kB
├ ◐ /[lang]/privacy                                       242 B          83.8 kB
├ ◐ /[lang]/search                                        5.32 kB         130 kB
├ ◐ /[lang]/sensitive                                     243 B          83.8 kB
├ ◐ /[lang]/sensitive/albums                              3.08 kB         100 kB
├ ◐ /[lang]/sensitive/albums/[album]                      2.41 kB         101 kB
├ ◐ /[lang]/sensitive/awards                              866 B          84.5 kB
├ ◐ /[lang]/sensitive/awards/[year]/[month]               866 B          84.5 kB
├ ◐ /[lang]/sensitive/awards/[year]/[month]/[day]         1.37 kB        91.6 kB
├ ◐ /[lang]/sensitive/collections                         143 B          93.3 kB
├ ◐ /[lang]/sensitive/collections/[collection]            1.71 kB         102 kB
├ ◐ /[lang]/sensitive/themes                              3.08 kB         100 kB
├ ◐ /[lang]/sensitive/themes/[year]/[month]               3.08 kB         100 kB
├ ◐ /[lang]/sensitive/themes/[year]/[month]/[day]         243 B          83.8 kB
├ ◐ /[lang]/sensitive/works                               243 B          83.8 kB
├ ◐ /[lang]/sensitive/works/[work]                        171 B           145 kB
├ ◐ /[lang]/sensitive/works/2.5d                          3.39 kB         115 kB
├ ◐ /[lang]/sensitive/works/2d                            3.4 kB          115 kB
├ ◐ /[lang]/sensitive/works/3d                            3.4 kB          115 kB
├ ◐ /[lang]/series                                        243 B          83.8 kB
├ ◐ /[lang]/settings                                      243 B          83.8 kB
├ ○ /[lang]/settings/interface                            899 B            95 kB
├ ○ /[lang]/settings/muted/tags                           1.63 kB         116 kB
├ ○ /[lang]/settings/muted/users                          990 B           116 kB
├ ○ /[lang]/settings/notification                         1 kB           95.1 kB
├ ○ /[lang]/settings/request                              4.07 kB        94.3 kB
├ ○ /[lang]/settings/restriction                          4.17 kB        94.4 kB
├ ◐ /[lang]/specified-commercial-transaction-act          243 B          83.8 kB
├ ◐ /[lang]/stamp-space                                   242 B          83.8 kB
├ ◐ /[lang]/stickers                                      156 B           109 kB
├ ◐ /[lang]/stickers/(..)stickers/[sticker]               2.06 kB         104 kB
├ ◐ /[lang]/stickers/[sticker]                            298 B          83.9 kB
├ ◐ /[lang]/stickers/downloads                            242 B          83.8 kB
├ ◐ /[lang]/stickers/search                               243 B          83.8 kB
├ ◐ /[lang]/stickers/search/[search]                      156 B           109 kB
├ ◐ /[lang]/support/chat                                  2.83 kB         128 kB
├ ◐ /[lang]/tags                                          243 B          83.8 kB
├ ◐ /[lang]/tags/[tag]                                    463 B          91.3 kB
├ ◐ /[lang]/terms                                         243 B          83.8 kB
├ ◐ /[lang]/themes                                        4.07 kB         101 kB
├ ◐ /[lang]/themes/[year]/[month]                         3.08 kB         100 kB
├ ◐ /[lang]/themes/[year]/[month]/[day]                   243 B          83.8 kB
├ ◐ /[lang]/users                                         243 B          83.8 kB
├ ◐ /[lang]/users/[user]                                  3.61 kB         101 kB
├ ◐ /[lang]/users/[user]/albums                           3.63 kB         101 kB
├ ◐ /[lang]/users/[user]/collections                      253 B          83.9 kB
├ ◐ /[lang]/users/[user]/notes                            251 B          83.9 kB
├ ◐ /[lang]/users/[user]/novels                           253 B          83.9 kB
├ ◐ /[lang]/users/[user]/stickers                         1.78 kB        99.2 kB
├ ◐ /[lang]/users/[user]/supports                         2.13 kB        92.3 kB
├ ◐ /[lang]/works                                         241 B          83.8 kB
├ ◐ /[lang]/works/[work]                                  172 B           145 kB
├ ◐ /[lang]/works/2.5d                                    3.39 kB         115 kB
├ ◐ /[lang]/works/2d                                      3.39 kB         115 kB
└ ◐ /[lang]/works/3d                                      3.4 kB          115 kB
+ First Load JS shared by all                             83.6 kB
  ├ chunks/9565-6e20d6639f22b5c7.js                       27.5 kB
  ├ chunks/bf6a786c-e18f99df5983eff6.js                   53.9 kB
  ├ chunks/main-app-5ca7b41e356b1572.js                   227 B
  └ chunks/webpack-87a61244e7aec903.js                    1.9 kB


ƒ Middleware                                              42.4 kB

○  (Static)             prerendered as static content
◐  (Partial Prerender)  prerendered as static HTML with dynamic server-streamed content
```

**Comment by Katsuyuki-Karasawa** [comment]
Server Action、GraphQL叩いてる以上必要なのか少し怪しいカモ🤔
[Server Actions が Next.js 14 からStableに！古参フロントエンドが消失しないために知っておくこと](https://zenn.dev/rgbkids/articles/a54f165dedde4f)

**Comment by Katsuyuki-Karasawa** [comment]
新規のAPIとかはないみたいなので、とりあえずTurbopackくらいですかね...

**Comment by Katsuyuki-Karasawa** [comment]
```bash
node_modules_next_3f8f89._.js?ts=1702321002203:18337 Uncaught Error: ./app/globals.css:977:22
Parsing css source code failed
  975 | }
  976 | .max-w-\[container\.sm\] {
> 977 |   max-width: container.sm;
      |                       ^
  978 | }
  979 | .max-w-lg {
  980 |   max-width: 32rem;

Expected Declaration value


    at <unknown> (Error: ./app/globals.css:977:22)
    at Object.getCompilationErrors (file://C:\Users\4ranc\Documents\github\aipictors\node_modules\next\dist\server\lib\router-utils\setup-dev-bundler.js:980:37)
    at DevBundlerService.getCompilationError (file://C:\Users\4ranc\Documents\github\aipictors\node_modules\next\dist\server\lib\dev-bundler-service.js:36:55)
    at DevServer.getCompilationError (file://C:\Users\4ranc\Documents\github\aipictors\node_modules\next\dist\server\dev\next-dev-server.js:582:42)
    at DevServer.findPageComponents (file://C:\Users\4ranc\Documents\github\aipictors\node_modules\next\dist\server\dev\next-dev-server.js:541:43)
    at async DevServer.renderErrorToResponseImpl (file://C:\Users\4ranc\Documents\github\aipictors\node_modules\next\dist\server\base-server.js:2050:26)
```

**Comment by Katsuyuki-Karasawa** [comment]
![image](https://github.com/aipictors/aipictors/assets/70247011/064290c7-6433-40bd-8fa4-98e687af0db0)
- https://nextjs.org/docs/messages/deopted-into-client-rendering
- https://zenn.dev/sasatech/articles/8a1d0c23fb2b2f
